#Robocode Compiler Properties
#Fri Mar 07 16:29:14 ICT 2025
compiler.options=
robocode.version=1.7.3.0
compiler.classpath=-classpath C\:\\Users\\X1\\Downloads\\eclipse-featureide\\jdk1.8.0_241\\jre/lib/rt.jar;libs\\robocode.jar;C\:\\Users\\X1\\Downloads\\TugasDua\\ModuleTester\\robocodes\\r1\\robots
compiler.binary=
